(() => {
 'use strict';
 const canvas=document.querySelector('#sea-gl'), particles=document.querySelector('#sea-motes'), image=new Image(), clearImage=new Image();
 const matteImage=new Image();let matteTexture,cloudField=null,matteOK=true;
 let mode='surface',draws=0,surfaceUpdates=0,deepUpdates=0;
 let windLast={x:.5,y:.5,at:0};
 function currentMode(){const idleAt=window.PachinDust?.coversSurface?.() ? .66 : 1;return progress<.63?'surface':progress<idleAt?'underwater':'contentidle';}
 function publish(){Object.assign(document.documentElement.dataset,{cloudMode:mode,draws:String(draws),simSteps:String(cloudField?.steps||0),surfaceUpdates:String(surfaceUpdates),deepUpdates:String(deepUpdates),cloudDisplacement:String(cloudField?.peakDisplacement||0),simGrid:cloudField?.grid||'off'});}
 const controller=new AbortController(), signal=controller.signal;
 let gl,program,texture,clearTexture,buffer,ctx,uniforms={},ready=false,dead=false,paused=false,raf=0,last=0,time=0,cloudTime=0,progress=0,w=1,h=1;
 const perfParams=new URLSearchParams(location.search), perfEnabled=perfParams.get('perf')==='1', perfProbe=perfParams.get('probe')==='1', perfSamples=[];
 let perfReadout=null;
 let perfLastOutput=0;
 const pointer={x:.5,y:.5,tx:.5,ty:.5,energy:0}; let motes=[],atmosphere=[],moonPoints=[],sprites={};
 const trail=Array.from({length:8},()=>({x:-2,y:-2,age:99}));let trailLast={x:-2,y:-2,at:-99};
 const vertex=`attribute vec2 position; varying vec2 uv; void main(){uv=(position+1.0)*0.5;gl_Position=vec4(position,0.0,1.0);}`;
 const fragment=`precision highp float;
 varying vec2 uv; uniform sampler2D painting,clearPainting,cloudMatte,cloudState;uniform float densityActive; uniform vec2 resolution,imageSize,pointer; uniform vec3 trail[8]; uniform float time,cloudTime,progress,energy;
 vec3 mod289(vec3 x){return x-floor(x*(1.0/289.0))*289.0;}
 vec2 mod289(vec2 x){return x-floor(x*(1.0/289.0))*289.0;}
 vec3 permute(vec3 x){return mod289(((x*34.0)+1.0)*x);}
 float snoise(vec2 v){const vec4 C=vec4(.211324865405187,.366025403784439,-.577350269189626,.024390243902439);vec2 i=floor(v+dot(v,C.yy));vec2 x0=v-i+dot(i,C.xx);vec2 i1=x0.x>x0.y?vec2(1.,0.):vec2(0.,1.);vec4 x12=x0.xyxy+C.xxzz;x12.xy-=i1;i=mod289(i);vec3 p=permute(permute(i.y+vec3(0.,i1.y,1.))+i.x+vec3(0.,i1.x,1.));vec3 m=max(.5-vec3(dot(x0,x0),dot(x12.xy,x12.xy),dot(x12.zw,x12.zw)),0.);m=m*m;m=m*m;vec3 x=2.*fract(p*C.www)-1.;vec3 h=abs(x)-.5;vec3 ox=floor(x+.5);vec3 a=x-ox;m*=1.79284291400159-.85373472095314*(a*a+h*h);vec3 g;g.x=a.x*x0.x+h.x*x0.y;g.yz=a.yz*x12.xz+h.yz*x12.yw;return 130.*dot(m,g);}
 float fbm(vec2 p){return snoise(p)*.57+snoise(p*2.03+4.2)*.28+snoise(p*4.11-2.7)*.15;}
 vec2 cover(vec2 q){float a=resolution.x/resolution.y,b=imageSize.x/imageSize.y;vec2 scale=a>b?vec2(1.,b/a):vec2(a/b,1.);return(q-.5)*scale+vec2(.5+.26*(1.-scale.x),.5);}
 void main(){
 vec2 screen=vec2(uv.x,1.-uv.y);float dive=smoothstep(.29,.66,progress);float transit=sin(dive*3.14159265);float line=.99-1.25*dive;float ripple=(sin(screen.x*18.+time*.75)+snoise(vec2(screen.x*8.,time*.16)))*.009*transit;float submerged=smoothstep(line-.045,line+.045,screen.y+ripple);float edge=exp(-pow((screen.y-line+ripple)*75.,2.))*transit;if(submerged*smoothstep(.29,.38,progress)>.999){float current=fbm(screen*vec2(3.2,2.1)+vec2(time*.025,-time*.018));vec3 under=mix(vec3(.025,.031,.039),vec3(.15,.18,.20),pow(1.-screen.y,1.6));under+=vec3(.035,.042,.050)*current;float shaft=0.;for(int i=0;i<4;i++){float k=float(i);float axis=.66+(k-1.5)*.17+(screen.y-.1)*(.12+(k-1.5)*.05);float bend=snoise(vec2(screen.y*2.+k,time*.055))*.025;shaft+=exp(-pow((screen.x-axis+bend)*(19.-k*2.),2.))*(.45+.2*sin(time*.24+k))*exp(-screen.y*1.8);}under+=vec3(.18,.20,.21)*shaft*.29;float caustic=pow(max(0.,snoise(screen*vec2(6.,3.)+time*.04)),5.);under+=vec3(.13,.15,.16)*caustic*(1.-screen.y)*.24;vec3 color=under+vec3(.42,.45,.47)*edge*.32;color*=1.-.1*pow(abs(screen.x-.5)*1.6,2.);gl_FragColor=vec4(color,1.);return;}
 vec2 q=cover(screen);q.y+=dive*.43;
 vec2 moonCenter=vec2(.759,.212);vec2 moonDelta=(q-moonCenter)*vec2(1.,.8);float moonRadius=length(moonDelta);float moonDisc=1.-smoothstep(.021,.032,moonRadius);float water=smoothstep(.576,.607,q.y);float cloud=(1.-water)*(1.-moonDisc);
 vec2 delta=vec2(fbm(q*vec2(3.,4.)+vec2(time*.018,0.)),fbm(q*4.+vec2(0.,time*.012)));
 vec2 cloudFlow=vec2(sin(cloudTime*.34+q.y*4.2)*.015+sin(cloudTime*.19+q.y*10.)*.006,sin(cloudTime*.27+q.x*5.1)*.005+snoise(q*6.+vec2(cloudTime*.09,-cloudTime*.04))*.004);
 vec2 cloudOffset=delta*vec2(.006,.003)+cloudFlow,cloudSample=q+cloudOffset;float sourceMoon=1.-smoothstep(.022,.035,length((cloudSample-moonCenter)*vec2(1.,.8)));vec2 sampleUV=q+cloud*cloudOffset*(1.-sourceMoon);float depth=clamp((q.y-.58)/.42,0.,1.);
 float wave=snoise(vec2(q.x*9.+time*.15,q.y*45.-time*.24));sampleUV.x+=water*(.002+depth*.006)*wave;sampleUV.y+=water*(.001+depth*.004)*sin(q.x*27.+q.y*110.-time*1.7+wave);
 vec2 md=screen-pointer;md.x*=resolution.x/resolution.y;float wake=exp(-dot(md,md)*65.3)*energy;
 sampleUV+=water*normalize(md+vec2(.001))*sin(length(md)*62.-time*3.)*wake*.0063;sampleUV+=vec2(sin(q.y*80.+time*1.4),cos(q.x*70.+time))*transit*.006;
 vec2 paintedUV=vec2(clamp(sampleUV.x,.001,.999),1.-clamp(sampleUV.y,.001,.999));vec3 sea=texture2D(painting,paintedUV).rgb;vec3 clearSea=texture2D(clearPainting,paintedUV).rgb;
 if(densityActive>.5&&water<1.){
  vec2 cloudQ=q+cloud*cloudOffset*(1.-sourceMoon);
  vec4 state=texture2D(cloudState,cloudQ);
  vec2 transported=cloudQ+(state.rg-vec2(128./255.))*.08;
  vec2 sourceUV=vec2(clamp(transported.x,.001,.999),1.-clamp(transported.y,.001,.999));
  float movedMoon=1.-smoothstep(.022,.038,length((transported-moonCenter)*vec2(1.,.8)));
  float opacity=texture2D(cloudMatte,sourceUV).r*clamp(state.b/max(state.a,.025),0.,1.);
  opacity*=1.-max(moonDisc,movedMoon);
  vec3 background=texture2D(clearPainting,vec2(clamp(q.x,.001,.999),1.-clamp(q.y,.001,.999))).rgb;
  vec3 foreground=texture2D(painting,sourceUV).rgb;
  vec3 cloudSky=mix(background,foreground,opacity);
  sea=mix(sea,cloudSky,1.-smoothstep(.54,.576,q.y));
 }
 float trailMask=0.;for(int i=0;i<8;i++){vec3 mark=trail[i];if(mark.z<3.05){float life=1.-smoothstep(2.45,3.05,mark.z);vec2 d=screen-mark.xy;d.x*=resolution.x/resolution.y;float wobble=.82+.24*snoise(mark.xy*13.+vec2(float(i)*3.1,time*.18));float rx=mix(.055,.15,life)*wobble*.7,ry=rx*(.62+.22*snoise(mark.xy*7.+float(i)));float blob=exp(-dot(d/vec2(rx,ry),d/vec2(rx,ry))*2.8);trailMask=max(trailMask,blob*life*(.72+.28*snoise(screen*18.+mark.xy*9.)));}}trailMask=clamp(trailMask,0.,1.);float reveal=trailMask*water*.15;sea=mix(sea,clearSea,reveal);
 vec2 fogP=(q-moonCenter)*vec2(18.,6.5)+vec2(cloudTime*.11,-cloudTime*.021);float fogWisp=smoothstep(-.02,.42,fbm(fogP)+snoise(fogP*2.+1.7)*.18);float moonFog=(1.-smoothstep(.018,.115,moonRadius))*fogWisp*(1.-water);sea=sea*(1.-moonFog*.23)+vec3(.34,.40,.41)*moonFog*.075;
 float reflection=exp(-pow((q.x-.759+wave*.012)*9.,2.))*water;float shard=pow(max(0.,snoise(vec2(q.x*110.+time*.4,q.y*290.-time*1.8))),4.);sea+=vec3(.68,.74,.71)*reflection*shard*.19;sea+=vec3(.13,.16,.17)*cloud*delta.x*.12;
 float current=fbm(screen*vec2(3.2,2.1)+vec2(time*.025,-time*.018));vec3 under=mix(vec3(.025,.031,.039),vec3(.15,.18,.20),pow(1.-screen.y,1.6));under+=vec3(.035,.042,.050)*current;
 float shaft=0.;for(int i=0;i<4;i++){float k=float(i);float axis=.66+(k-1.5)*.17+(screen.y-.1)*(.12+(k-1.5)*.05);float bend=snoise(vec2(screen.y*2.+k,time*.055))*.025;shaft+=exp(-pow((screen.x-axis+bend)*(19.-k*2.),2.))*(.45+.2*sin(time*.24+k))*exp(-screen.y*1.8);}
 under+=vec3(.18,.20,.21)*shaft*.29;float caustic=pow(max(0.,snoise(screen*vec2(6.,3.)+time*.04)),5.);under+=vec3(.13,.15,.16)*caustic*(1.-screen.y)*.24;
 submerged*=smoothstep(.29,.38,progress);
 vec3 color=mix(sea,under,submerged);color+=vec3(.42,.45,.47)*edge*.32;color*=1.-.1*pow(abs(screen.x-.5)*1.6,2.);gl_FragColor=vec4(color,1.);
 }`;
 function status(message){const el=document.querySelector('#render-status');el.textContent=message;el.hidden=!message;}
 function makeSprite(color){const sprite=document.createElement('canvas');sprite.width=sprite.height=12;const brush=sprite.getContext('2d'),halo=brush.createRadialGradient(6,6,0,6,6,6);halo.addColorStop(0,color);halo.addColorStop(.26,color);halo.addColorStop(1,'rgba(0,0,0,0)');brush.fillStyle=halo;brush.fillRect(0,0,12,12);return sprite;}
 function recordPerf(now,delta){if(!perfEnabled)return;perfReadout??=document.querySelector('#perf-readout');if(!perfReadout){perfReadout=document.createElement('output');perfReadout.id='perf-readout';perfReadout.setAttribute('aria-live','polite');document.querySelector('.motion-controls')?.prepend(perfReadout);}if(!perfReadout)return;perfSamples.push({now,delta});while(perfSamples.length&&now-perfSamples[0].now>5000)perfSamples.shift();if(now-perfLastOutput<250)return;perfLastOutput=now;const deltas=perfSamples.map(sample=>sample.delta).sort((a,b)=>a-b),count=deltas.length,total=deltas.reduce((sum,value)=>sum+value,0),p95=deltas[Math.min(count-1,Math.max(0,Math.ceil(count*.95)-1))]||0,fps=total?count*1000/total:0;perfReadout.hidden=false;perfReadout.textContent=`${perfProbe?'probe · ':''}${fps.toFixed(1)} fps · p95 ${p95.toFixed(1)} ms · n ${count} · ${canvas.width}×${canvas.height} · surface ${atmosphere.length}+${moonPoints.length} · deep ${motes.length} · p ${progress.toFixed(3)}`;}
 function fail(error){ready=false;stop();canvas.style.visibility='hidden';document.documentElement.dataset.renderer='fallback';status('Motion rendering unavailable · fallback image retained');console.warn(error);}
 function compile(type,source){const shader=gl.createShader(type);gl.shaderSource(shader,source);gl.compileShader(shader);if(!gl.getShaderParameter(shader,gl.COMPILE_STATUS)){const error=gl.getShaderInfoLog(shader);gl.deleteShader(shader);throw new Error(error)}return shader;}
 function init(){if(dead)return;try{
 gl=canvas.getContext('webgl',{alpha:false,antialias:false,powerPreference:'high-performance'});if(!gl)throw new Error('WebGL unavailable');const v=compile(gl.VERTEX_SHADER,vertex),f=compile(gl.FRAGMENT_SHADER,fragment);program=gl.createProgram();gl.attachShader(program,v);gl.attachShader(program,f);gl.linkProgram(program);gl.deleteShader(v);gl.deleteShader(f);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw new Error(gl.getProgramInfoLog(program));
 gl.useProgram(program);buffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([-1,-1,1,-1,-1,1,-1,1,1,-1,1,1]),gl.STATIC_DRAW);const location=gl.getAttribLocation(program,'position');gl.enableVertexAttribArray(location);gl.vertexAttribPointer(location,2,gl.FLOAT,false,0,0);
 function makeTexture(source){const target=gl.createTexture();gl.bindTexture(gl.TEXTURE_2D,target);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);gl.pixelStorei(gl.UNPACK_FLIP_Y_WEBGL,true);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,gl.RGBA,gl.UNSIGNED_BYTE,source);return target;}texture=makeTexture(image);clearTexture=makeTexture(clearImage);
 gl.activeTexture(gl.TEXTURE2);matteTexture=makeTexture(matteOK?matteImage:clearImage);
 if(matteOK)cloudField=window.createCloudDensity(gl,matteImage);
 for(const name of ['painting','clearPainting','cloudMatte','cloudState','densityActive','resolution','imageSize','pointer','time','cloudTime','progress','energy'])uniforms[name]=gl.getUniformLocation(program,name);uniforms.trail=Array.from({length:8},(_,i)=>gl.getUniformLocation(program,`trail[${i}]`));
 ctx=particles.getContext('2d');ready=true;canvas.style.visibility='visible';document.documentElement.dataset.renderer='webgl';status('');resize();render(0);start();
 }catch(error){fail(error)}}
 function resize(){w=innerWidth;h=innerHeight;const pixelBudget=w<600?900000:1800000,dpr=Math.min(devicePixelRatio||1,1.25,Math.max(1,Math.sqrt(pixelBudget/(w*h))));for(const c of [canvas,particles]){c.width=Math.round(w*dpr);c.height=Math.round(h*dpr)}if(gl)gl.viewport(0,0,canvas.width,canvas.height);if(ctx)ctx.setTransform(dpr,0,0,dpr,0,0);const unit=i=>((Math.sin(i*83.1)*43758.5)%1+1)%1;motes=Array.from({length:w<600?72:130},(_,i)=>({x:((Math.sin(i*83.1)*43758.5)%1+1)%1*w,y:((Math.sin(i*29.3)*17528.3)%1+1)%1*h,phase:i*2.39,size:.65+(i%4)*.35}));atmosphere=Array.from({length:w<600?26:48},(_,i)=>({x:unit(i*4.1)*w,y:(.08+unit(i*5.7)*.66)*h,vx:(unit(i*7.3)*2+1)*(i%2?1:-1),vy:(unit(i*9.1)*1.2+.25)*(i%3?1:-1),phase:i*1.71,size:.55+unit(i*11.3)*.45,near:i%4===0}));moonPoints=Array.from({length:w<600?6:12},(_,i)=>{const gx=unit(i*13.1)+unit(i*15.7)+unit(i*18.3)-1.5,gy=unit(i*21.1)+unit(i*23.9)+unit(i*27.7)-1.5;let ox=gx*.046,oy=gy*.037;if(Math.hypot(ox,oy)<.022)ox+=(ox<0?-.027:.027);const kind=i%10===0?'lavender':i%10===1?'gold':'silver';return{ox,oy,phase:i*2.13,size:.5+unit(i*19.7)*.8,kind}});sprites={atmosphere:makeSprite('rgba(202,218,214,1)'),moonSilver:makeSprite('rgba(225,234,226,1)'),moonGold:makeSprite('rgba(219,201,156,1)'),moonLavender:makeSprite('rgba(191,185,210,1)')};if(ready)render(0);}
 function render(dt,cloudElapsed=dt){if(!ready||dead)return;if(dt){time+=dt;pointer.x+=(pointer.tx-pointer.x)*(1-Math.exp(-dt*7));pointer.y+=(pointer.ty-pointer.y)*(1-Math.exp(-dt*7));pointer.energy*=Math.exp(-dt*1.6);for(const mark of trail)mark.age+=dt;}if(cloudElapsed&&mode==='surface'){cloudTime+=cloudElapsed;cloudField?.advance(Math.min(cloudElapsed,2/30));}
 gl.useProgram(program);gl.activeTexture(gl.TEXTURE2);gl.bindTexture(gl.TEXTURE_2D,matteTexture);gl.activeTexture(gl.TEXTURE3);gl.bindTexture(gl.TEXTURE_2D,cloudField?.texture||clearTexture);
 gl.uniform1i(uniforms.cloudMatte,2);gl.uniform1i(uniforms.cloudState,3);gl.uniform1f(uniforms.densityActive,cloudField?1:0);
 gl.activeTexture(gl.TEXTURE0);gl.bindTexture(gl.TEXTURE_2D,texture);gl.activeTexture(gl.TEXTURE1);gl.bindTexture(gl.TEXTURE_2D,clearTexture);gl.uniform1i(uniforms.painting,0);gl.uniform1i(uniforms.clearPainting,1);gl.uniform2f(uniforms.resolution,canvas.width,canvas.height);gl.uniform2f(uniforms.imageSize,image.width,image.height);gl.uniform2f(uniforms.pointer,pointer.x,pointer.y);for(let i=0;i<8;i++)gl.uniform3f(uniforms.trail[i],trail[i].x,trail[i].y,trail[i].age);gl.uniform1f(uniforms.time,time);gl.uniform1f(uniforms.cloudTime,cloudTime);gl.uniform1f(uniforms.progress,progress);gl.uniform1f(uniforms.energy,pointer.energy);gl.drawArrays(gl.TRIANGLES,0,6);draws++;
 if(ctx){ctx.clearRect(0,0,w,h);const deep=Math.min(1,Math.max(0,(progress-.4)*4)),surfaceFade=1-Math.min(1,Math.max(0,(progress-.24)/.28)),deepFade=Math.min(1,Math.max(0,(progress-.32)/.22)),viewportAspect=w/h,imageAspect=image.width/image.height,coverX=viewportAspect>imageAspect?1:viewportAspect/imageAspect,coverY=viewportAspect>imageAspect?imageAspect/viewportAspect:1,diveT=Math.min(1,Math.max(0,(progress-.29)/.37)),dive=diveT*diveT*(3-2*diveT),fullDiveT=Math.min(1,Math.max(0,(progress-.60)/.06)),fullDive=fullDiveT*fullDiveT*(3-2*fullDiveT);if(dt&&surfaceFade)surfaceUpdates++;if(dt&&deepFade)deepUpdates++;if(dt&&surfaceFade)for(const mote of atmosphere){mote.x=(mote.x+mote.vx*dt+w)%w;mote.y=(mote.y+mote.vy*dt+h)%h;}if(surfaceFade){for(const mote of atmosphere){const breath=.72+.28*Math.sin(cloudTime*.62+mote.phase),size=mote.size*4;ctx.globalAlpha=surfaceFade*(mote.near?.22+breath*.08:.12+breath*.07);ctx.drawImage(sprites.atmosphere,mote.x-size*.5,mote.y-size*.5,size,size);}const moonX=((.759-.5-.26*(1-coverX))/coverX+.5)*w,moonY=((.212-dive*.43-.5)/coverY+.5)*h;for(const mote of moonPoints){const driftX=Math.sin(cloudTime*(.72+(mote.phase%3)*.12)+mote.phase)*.0018,driftY=Math.cos(cloudTime*(.54+(mote.phase%4)*.10)+mote.phase)*.0012,size=mote.size*4,breath=.64+.36*Math.sin(cloudTime*(.72+(mote.phase%4)*.11)+mote.phase),sprite=mote.kind==='gold'?sprites.moonGold:mote.kind==='lavender'?sprites.moonLavender:sprites.moonSilver;ctx.globalAlpha=surfaceFade*(.48+.18*breath);ctx.drawImage(sprite,moonX+(mote.ox+driftX)/coverX*w-size*.5,moonY+(mote.oy+driftY)/coverY*h-size*.5,size,size);}}ctx.globalAlpha=1;if(deepFade)for(const q of motes){const horizonQ=(q.y/h-.5)*coverY+.5+dive*.43,waterT=Math.min(1,Math.max(0,(horizonQ-.576)/.031)),particleWater=Math.max(waterT*waterT*(3-2*waterT),fullDive),dx=q.x-pointer.x*w,dy=q.y-pointer.y*h,dist=Math.hypot(dx,dy),force=particleWater*Math.max(0,1-dist/105)*pointer.energy;if(dt){q.x+=dt*(5+Math.sin(q.phase+q.y*.008+time*.3)*7+dy*force*.5);q.y+=dt*((deep?-5:18)+Math.cos(q.phase+time*.3)*3-dx*force*.5);q.x=(q.x+w)%w;q.y=(q.y+h)%h}ctx.fillStyle=`rgba(204,225,220,${deepFade*(.09+deep*.15+force*.25)})`;ctx.fillRect(q.x,q.y,q.size,deep?q.size:5);}ctx.globalAlpha=1;}publish();}
 function loop(now){raf=0;if(!ready||dead||paused||document.hidden||mode==='contentidle')return;const actualDelta=Math.max(0,now-last),dt=Math.min(.04,actualDelta/1000),cloudElapsed=Math.min(2,actualDelta/1000);last=now;recordPerf(now,actualDelta);if(!perfProbe)render(dt,cloudElapsed);raf=requestAnimationFrame(loop);}
 function start(){if(raf||!ready||dead||paused||document.hidden||mode==='contentidle')return;perfSamples.length=0;last=performance.now();raf=requestAnimationFrame(loop)}function stop(){if(raf)cancelAnimationFrame(raf);raf=0;}
 window.PachinSea={setProgress(p){const previous=progress,previousMode=mode;progress=Math.min(1,Math.max(0,Number(p)||0));mode=currentMode();if(mode!==previousMode)cloudField?.clearWind();if(mode==='contentidle'){stop();if(previousMode!==mode)render(0);if(perfReadout)perfReadout.textContent='content idle · 0 continuous draws';}else{if(paused&&previous!==progress)render(0);start();}publish();},setPaused(value){paused=!!value;if(paused){stop();render(0)}else start()},destroy(){dead=true;ready=false;stop();controller.abort();image.onload=null;image.onerror=null;clearImage.onload=null;clearImage.onerror=null;matteImage.onload=null;matteImage.onerror=null;cloudField?.destroy();if(gl){gl.deleteTexture(matteTexture);}if(gl){gl.deleteTexture(texture);gl.deleteTexture(clearTexture);gl.deleteBuffer(buffer);gl.deleteProgram(program)}}};
 addEventListener('pointermove',e=>{if(e.pointerType==='touch'||paused||mode==='contentidle')return;
 if(mode==='surface'&&cloudField){const now=performance.now(),x=e.clientX/w,y=e.clientY/h,gap=now-windLast.at,seconds=Math.max(.004,gap/1000),a=w/h,b=image.width/image.height,cx=a>b?1:a/b,cy=a>b?b/a:1,t=Math.min(1,Math.max(0,(progress-.29)/.37)),dive=t*t*(3-2*t);
 // Use the real event interval, not a 60 Hz assumption. First entry must not create a gust.
 if(windLast.at&&gap<150&&!e.target.closest?.('header,button,a'))cloudField.pointer((x-.5)*cx+.5+.26*(1-cx),(y-.5)*cy+.5+dive*.43,(x-windLast.x)/seconds*cx,(y-windLast.y)/seconds*cy);windLast={x,y,at:now};}
 pointer.tx=e.clientX/w;pointer.ty=e.clientY/h;pointer.energy=Math.min(1,pointer.energy+.2);if(Math.hypot(pointer.tx-trailLast.x,pointer.ty-trailLast.y)>.012||time-trailLast.at>.12){trail.pop();trail.unshift({x:pointer.tx,y:pointer.ty,age:0});trailLast={x:pointer.tx,y:pointer.ty,at:time};}},{passive:true,signal});addEventListener('resize',resize,{signal});document.addEventListener('visibilitychange',()=>{if(document.hidden){stop();cloudField?.clearWind();}else start()},{signal});
 function clearPointerWind(){windLast.at=0;cloudField?.clearWind();}
 addEventListener('blur',clearPointerWind,{signal});document.addEventListener('pointerout',e=>{if(!e.relatedTarget)clearPointerWind();},{signal});
 addEventListener('pagehide',e=>{if(e.persisted)stop();else window.PachinSea.destroy()},{signal});addEventListener('pageshow',()=>start(),{signal});canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();fail('WebGL context lost')},{signal});canvas.addEventListener('webglcontextrestored',init,{signal});
 let loadedImages=0;function onImageLoad(){if(++loadedImages===3)init();}image.onload=onImageLoad;clearImage.onload=onImageLoad;matteImage.onload=onImageLoad;matteImage.onerror=()=>{matteOK=false;onImageLoad();};image.onerror=()=>fail('Painting failed to load');clearImage.onerror=()=>fail('Clear painting failed to load');matteImage.src='../assets/cloud-density-matte-v1.png';image.src='../assets/moonlit-material.png';clearImage.src='../assets/moonlit-clear.png';
})();
